apiVersion: v1
kind: Service
metadata:
  name: ${BASE_NAME}
  labels:
    name: nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    name: ${BASE_NAME}-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${BASE_NAME}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ${BASE_NAME}-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: ${BASE_NAME}-nginx
        tier: frontend
        release: stable
    spec:
      containers:
      - name: ${BASE_NAME}-nginx
        image: ${NGINX_IMAGE}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 2
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 25Mi

