apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-svc-label
  name: ${BASE_NAME}-service
spec:
  ports:
    - port: ${PORT}
  selector:
    app: ${BASE_NAME}-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ENVIRONMENT}-${BASE_NAME}
spec:
  selector:
    matchLabels:
      app: ${BASE_NAME}-api
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ${BASE_NAME}-api
    spec:
      containers:
        - name: ${BASE_NAME}-container
          image: '${CONTAINER_IMAGE}'
          env:
          - name: MONGO_PORT
            value: '${GLANZ_MONGO_PORT}'
          - name: MONGO_HOST
            value: '${GLANZ_MONGO_HOST}'
          ports:
            - containerPort: ${PORT}
          livenessProbe:
            tcpSocket:
              port: ${PORT}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: ${PORT}
            initialDelaySeconds: 10
            timeoutSeconds: 5
